import { Link } from 'react-router-dom';
import { ArrowUpRight, BarChart3, Clock3, DollarSign, Package, Plus, ShoppingBag } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { sampleOrders, sampleProducts } from '../../data/marketplaceData';
import { Currency, PageHeading, StatusBadge, VendorLayout } from '../../components/VendorLayout';

const orderStatus = (status: string) => status === 'new' ? 'Pending' : status === 'delivered' ? 'Delivered' : status === 'out_for_delivery' ? 'Shipped' : 'Processing';

export const BusinessDashboard = () => {
  const { business } = useAuth();
  const businessId = business?.id || 'biz-1';
  const orders = sampleOrders.filter((order) => order.businessId === businessId);
  const products = sampleProducts.filter((product) => product.businessId === businessId);
  const visibleOrders = orders.length ? orders : sampleOrders.slice(0, 3);
  const visibleProducts = products.length ? products : sampleProducts.slice(0, 5);
  const sales = visibleOrders.reduce((sum, order) => sum + order.total, 0) || 1250;
  const pending = visibleOrders.filter((order) => ['new', 'confirmed', 'preparing'].includes(order.orderStatus)).length || 7;
  const chart = [34, 48, 43, 68, 54, 78, 64, 92, 76, 86, 72, 100];

  return <VendorLayout title="Dashboard"><PageHeading eyebrow="Tuesday, September 5" title={`Welcome back, ${business?.name || 'Vendor'} 👋`} description="Manage your store, products and orders from one place." />
    <div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-7">
      {[{ label: "Today's Sales", value: <Currency value={sales} />, change: '+12.5%', icon: DollarSign }, { label: 'Orders', value: orders.length || 24, change: '+8.2%', icon: ShoppingBag }, { label: 'Products', value: products.length || 86, change: '+5.0%', icon: Package }, { label: 'Pending Orders', value: pending, change: 'Needs attention', icon: Clock3 }].map(({ label, value, change, icon: Icon }) => <div key={label} className="bg-white border border-[#eee5df] rounded-2xl p-4 sm:p-5 shadow-[0_4px_18px_rgba(74,43,28,0.04)]"><div className="flex items-start justify-between gap-2"><div className="w-10 h-10 rounded-xl bg-[#f5ebe5] text-[#70402b] flex items-center justify-center"><Icon className="w-5 h-5" /></div><span className="text-[11px] font-semibold text-[#3c8753] bg-[#eaf5eb] px-2 py-1 rounded-full">{change}</span></div><p className="text-xs text-[#927f74] mt-4">{label}</p><p className="text-xl sm:text-2xl font-bold mt-1 text-[#2d211b]">{value}</p></div>)}
    </div>

    <div className="grid xl:grid-cols-[1.55fr_1fr] gap-6 mb-7">
      <section className="bg-white border border-[#eee5df] rounded-2xl p-5 sm:p-6 shadow-[0_4px_18px_rgba(74,43,28,0.04)]"><div className="flex items-start justify-between gap-3 mb-6"><div><h2 className="text-lg font-bold">Sales Overview</h2><p className="text-xs text-[#927f74] mt-1">Your store revenue over time</p></div><select className="border border-[#e7ddd7] rounded-lg px-3 py-2 text-xs bg-white text-[#6f5c50]" defaultValue="7 Days"><option>7 Days</option><option>30 Days</option><option>3 Months</option></select></div><div className="h-56 relative"><div className="absolute inset-0 flex flex-col justify-between text-[10px] text-[#b09f95]"><span>GH₵ 2,000</span><span>GH₵ 1,500</span><span>GH₵ 1,000</span><span>GH₵ 500</span><span>GH₵ 0</span></div><div className="absolute left-14 right-0 inset-y-0 flex flex-col justify-between">{[0, 1, 2, 3, 4].map((line) => <div key={line} className="border-t border-dashed border-[#eee5df]" />)}<svg className="absolute inset-0 h-full w-full overflow-visible" viewBox="0 0 600 210" preserveAspectRatio="none"><polyline points={chart.map((point, index) => `${index * 54},${210 - point * 1.8}`).join(' ')} fill="none" stroke="#6f3d27" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{chart.map((point, index) => <circle key={index} cx={index * 54} cy={210 - point * 1.8} r="4" fill="#fff" stroke="#6f3d27" strokeWidth="2" />)}</svg></div></div><div className="ml-14 flex justify-between text-[10px] text-[#b09f95] mt-2"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></section>
      <section className="bg-[#3f2418] rounded-2xl p-5 sm:p-6 text-white relative overflow-hidden"><div className="absolute -right-14 -top-14 w-44 h-44 rounded-full border-[25px] border-white/5" /><div className="relative"><p className="text-xs uppercase tracking-[0.18em] text-[#d8b7a3]">Store health</p><h2 className="text-2xl font-bold mt-3">Keep your store moving</h2><p className="text-sm leading-6 text-[#e5d4ca] mt-3">Add products, respond to orders, and keep your customers coming back.</p><div className="mt-8 h-2 bg-white/15 rounded-full"><div className="w-[76%] h-full rounded-full bg-[#d7a86e]" /></div><div className="flex justify-between text-xs text-[#d8b7a3] mt-2"><span>Store setup</span><span>76%</span></div><Link to="/business/store" className="inline-flex items-center gap-2 mt-7 text-sm font-semibold text-white hover:text-[#f1d8c6]">Complete store profile <ArrowUpRight className="w-4 h-4" /></Link></div></section>
    </div>

    <section className="flex flex-wrap gap-3 mb-7"><Link to="/business/products/add" className="inline-flex items-center gap-2 rounded-xl bg-[#6f3d27] text-white px-4 py-3 text-sm font-semibold hover:bg-[#54301f] transition"><Plus className="w-4 h-4" />Add Product</Link><Link to="/business/orders" className="inline-flex items-center gap-2 rounded-xl bg-white border border-[#e7ddd7] text-[#4e362a] px-4 py-3 text-sm font-semibold hover:bg-[#f7f1ed] transition"><ShoppingBag className="w-4 h-4" />View Orders</Link><Link to="/business/store" className="inline-flex items-center gap-2 rounded-xl bg-white border border-[#e7ddd7] text-[#4e362a] px-4 py-3 text-sm font-semibold hover:bg-[#f7f1ed] transition"><BarChart3 className="w-4 h-4" />Edit Store</Link></section>

    <div className="grid xl:grid-cols-[1.5fr_1fr] gap-6"><section className="bg-white border border-[#eee5df] rounded-2xl shadow-[0_4px_18px_rgba(74,43,28,0.04)] overflow-hidden"><div className="p-5 sm:p-6 flex items-center justify-between border-b border-[#f1ebe7]"><div><h2 className="text-lg font-bold">Recent Orders</h2><p className="text-xs text-[#927f74] mt-1">The latest activity from your customers</p></div><Link to="/business/orders" className="text-xs font-semibold text-[#6f3d27]">View all orders</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[620px]"><thead><tr className="bg-[#fcfaf9] text-left text-[11px] uppercase tracking-wide text-[#9a887d]"><th className="px-5 py-3">Order ID</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Product</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Date</th></tr></thead><tbody>{visibleOrders.map((order) => <tr key={order.id} className="border-t border-[#f1ebe7] text-sm"><td className="px-5 py-4 font-semibold text-[#5f3928]">#{order.id.slice(-4)}</td><td className="px-5 py-4">{order.customerName}</td><td className="px-5 py-4 text-[#806e64]">{order.items[0]?.productName}</td><td className="px-5 py-4 font-semibold"><Currency value={order.total} /></td><td className="px-5 py-4"><StatusBadge status={orderStatus(order.orderStatus)} /></td><td className="px-5 py-4 text-[#927f74]">{new Date(order.createdAt).toLocaleDateString('en-GH', { month: 'short', day: 'numeric' })}</td></tr>)}</tbody></table></div></section><section className="bg-white border border-[#eee5df] rounded-2xl shadow-[0_4px_18px_rgba(74,43,28,0.04)]"><div className="p-5 sm:p-6 border-b border-[#f1ebe7] flex items-center justify-between"><div><h2 className="text-lg font-bold">Top Products</h2><p className="text-xs text-[#927f74] mt-1">Your best-selling items</p></div><Link to="/business/products" className="text-xs font-semibold text-[#6f3d27]">Manage</Link></div><div className="p-5 sm:p-6 space-y-4">{visibleProducts.slice(0, 5).map((product) => <div key={product.id} className="flex items-center gap-3"><div className="w-11 h-11 rounded-xl bg-[#f5ebe5] flex items-center justify-center overflow-hidden"><img src={product.images[0]} alt="" className="w-full h-full object-cover" onError={(event) => { event.currentTarget.style.display = 'none'; }} /><Package className="w-5 h-5 text-[#70402b]" /></div><div className="flex-1 min-w-0"><p className="text-sm font-semibold truncate">{product.name}</p><p className="text-xs text-[#927f74]">{product.salesCount || 24} sold</p></div><p className="text-sm font-bold"><Currency value={(product.salesCount || 24) * product.price} /></p></div>)}</div></section></div>
  </VendorLayout>;
};
